CREATE TABLE IF NOT EXISTS PROFILES
(
    ID          UUID PRIMARY KEY,
    CREATED_AT  TIMESTAMP(9) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_AT TIMESTAMP(9) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE IF NOT EXISTS GENERAL_ATTACHMENT
(
    PROFILE_ID       UUID PRIMARY KEY,
    LAST_KNOWN_NAME  VARCHAR(16)                 NULL,
    PREFERRED_LOCALE VARCHAR(64) DEFAULT 'en-US' NOT NULL,
    CONSTRAINT FK_GENERAL_ATTACHMENT_PROFILE_ID__ID FOREIGN KEY (PROFILE_ID) REFERENCES PROFILES (ID) ON DELETE CASCADE ON UPDATE RESTRICT
);
CREATE TABLE IF NOT EXISTS EFFORT_SHOP_ATTACHMENT
(
    PROFILE_ID     UUID PRIMARY KEY,
    EFFORT_BALANCE INT DEFAULT 0 NOT NULL,
    CONSTRAINT FK_EFFORT_SHOP_ATTACHMENT_PROFILE_ID__ID FOREIGN KEY (PROFILE_ID) REFERENCES PROFILES (ID) ON DELETE CASCADE ON UPDATE RESTRICT
);
