CREATE TABLE IF NOT EXISTS PUNISHMENTS
(
    ID                   INT AUTO_INCREMENT PRIMARY KEY,
    CASE_ID              VARCHAR(32)  NOT NULL,
    PUNISHED_PROFILE_ID  UUID         NOT NULL,
    PUNISHMENT_TYPE      VARCHAR(32)  NOT NULL,
    REASON               TEXT         NOT NULL,
    PUNISHMENT_SEVERITY  VARCHAR(32)  NOT NULL,
    PUNISHMENT_TIMESTAMP TIMESTAMP(9) NOT NULL,
    ISSUER_PROFILE_ID    UUID         NOT NULL,
    CONSTRAINT FK_PUNISHMENTS_PUNISHED_PROFILE_ID__ID FOREIGN KEY (PUNISHED_PROFILE_ID) REFERENCES PROFILES (ID) ON UPDATE RESTRICT,
    CONSTRAINT FK_PUNISHMENTS_ISSUER_PROFILE_ID__ID FOREIGN KEY (ISSUER_PROFILE_ID) REFERENCES PROFILES (ID) ON UPDATE RESTRICT
);
ALTER TABLE PUNISHMENTS
    ADD CONSTRAINT PUNISHMENTS_CASE_ID_UNIQUE UNIQUE (CASE_ID);
