ktor {
    deployment {
        port = 8080
        watch = [ net.tjalp.nexus.backend ]
    }
    application {
        modules = [ net.tjalp.nexus.backend.ApplicationKt.module ]
    }
    generator {
        trace = true
    }
}
